/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pet Store
 * OpenAPI spec version: 2.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  NotFoundError,
  Toy,
  ToysCreateToyParams,
  ToysDeleteToyParams,
  ToysListToysParams,
  ToysUpdateToyParams,
  UnauthorizedError,
  ValidationError,
} from "../../models";

export const getToysListToysUrl = (
  petId: number,
  params?: ToysListToysParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/pets/${petId}/toys?${stringifiedParams}`
    : `/pets/${petId}/toys`;
};

export const toysListToys = async (
  petId: number,
  params?: ToysListToysParams,
  options?: RequestInit,
): Promise<Toy[]> => {
  const res = await fetch(getToysListToysUrl(petId, params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: Toy[] = body ? JSON.parse(body) : {};

  return data;
};

export const getToysListToysQueryKey = (
  petId?: number,
  params?: ToysListToysParams,
) => {
  return [`/pets/${petId}/toys`, ...(params ? [params] : [])] as const;
};

export const getToysListToysQueryOptions = <
  TData = Awaited<ReturnType<typeof toysListToys>>,
  TError = NotFoundError,
>(
  petId: number,
  params?: ToysListToysParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof toysListToys>>,
      TError,
      TData
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getToysListToysQueryKey(petId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof toysListToys>>> = ({
    signal,
  }) => toysListToys(petId, params, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!petId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof toysListToys>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ToysListToysQueryResult = NonNullable<
  Awaited<ReturnType<typeof toysListToys>>
>;
export type ToysListToysQueryError = NotFoundError;

export function useToysListToys<
  TData = Awaited<ReturnType<typeof toysListToys>>,
  TError = NotFoundError,
>(
  petId: number,
  params?: ToysListToysParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof toysListToys>>,
      TError,
      TData
    >;
    fetch?: RequestInit;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getToysListToysQueryOptions(petId, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getToysCreateToyUrl = (
  petId: number,
  params?: ToysCreateToyParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/pets/${petId}/toys?${stringifiedParams}`
    : `/pets/${petId}/toys`;
};

export const toysCreateToy = async (
  petId: number,
  toy: Toy,
  params?: ToysCreateToyParams,
  options?: RequestInit,
): Promise<Toy> => {
  const res = await fetch(getToysCreateToyUrl(petId, params), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(toy),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: Toy = body ? JSON.parse(body) : {};

  return data;
};

export const getToysCreateToyMutationOptions = <
  TError = ValidationError | UnauthorizedError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toysCreateToy>>,
    TError,
    { petId: number; data: Toy; params?: ToysCreateToyParams },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof toysCreateToy>>,
  TError,
  { petId: number; data: Toy; params?: ToysCreateToyParams },
  TContext
> => {
  const mutationKey = ["toysCreateToy"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof toysCreateToy>>,
    { petId: number; data: Toy; params?: ToysCreateToyParams }
  > = (props) => {
    const { petId, data, params } = props ?? {};

    return toysCreateToy(petId, data, params, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ToysCreateToyMutationResult = NonNullable<
  Awaited<ReturnType<typeof toysCreateToy>>
>;
export type ToysCreateToyMutationBody = Toy;
export type ToysCreateToyMutationError = ValidationError | UnauthorizedError;

export const useToysCreateToy = <
  TError = ValidationError | UnauthorizedError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toysCreateToy>>,
    TError,
    { petId: number; data: Toy; params?: ToysCreateToyParams },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationResult<
  Awaited<ReturnType<typeof toysCreateToy>>,
  TError,
  { petId: number; data: Toy; params?: ToysCreateToyParams },
  TContext
> => {
  const mutationOptions = getToysCreateToyMutationOptions(options);

  return useMutation(mutationOptions);
};
export const getToysUpdateToyUrl = (
  petId: number,
  toyId: number,
  params?: ToysUpdateToyParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/pets/${petId}/toys/${toyId}?${stringifiedParams}`
    : `/pets/${petId}/toys/${toyId}`;
};

export const toysUpdateToy = async (
  petId: number,
  toyId: number,
  toy: Toy,
  params?: ToysUpdateToyParams,
  options?: RequestInit,
): Promise<Toy> => {
  const res = await fetch(getToysUpdateToyUrl(petId, toyId, params), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(toy),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: Toy = body ? JSON.parse(body) : {};

  return data;
};

export const getToysUpdateToyMutationOptions = <
  TError = ValidationError | UnauthorizedError | NotFoundError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toysUpdateToy>>,
    TError,
    { petId: number; toyId: number; data: Toy; params?: ToysUpdateToyParams },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof toysUpdateToy>>,
  TError,
  { petId: number; toyId: number; data: Toy; params?: ToysUpdateToyParams },
  TContext
> => {
  const mutationKey = ["toysUpdateToy"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof toysUpdateToy>>,
    { petId: number; toyId: number; data: Toy; params?: ToysUpdateToyParams }
  > = (props) => {
    const { petId, toyId, data, params } = props ?? {};

    return toysUpdateToy(petId, toyId, data, params, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ToysUpdateToyMutationResult = NonNullable<
  Awaited<ReturnType<typeof toysUpdateToy>>
>;
export type ToysUpdateToyMutationBody = Toy;
export type ToysUpdateToyMutationError =
  | ValidationError
  | UnauthorizedError
  | NotFoundError;

export const useToysUpdateToy = <
  TError = ValidationError | UnauthorizedError | NotFoundError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toysUpdateToy>>,
    TError,
    { petId: number; toyId: number; data: Toy; params?: ToysUpdateToyParams },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationResult<
  Awaited<ReturnType<typeof toysUpdateToy>>,
  TError,
  { petId: number; toyId: number; data: Toy; params?: ToysUpdateToyParams },
  TContext
> => {
  const mutationOptions = getToysUpdateToyMutationOptions(options);

  return useMutation(mutationOptions);
};
export const getToysDeleteToyUrl = (
  petId: number,
  toyId: number,
  params?: ToysDeleteToyParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/pets/${petId}/toys/${toyId}?${stringifiedParams}`
    : `/pets/${petId}/toys/${toyId}`;
};

export const toysDeleteToy = async (
  petId: number,
  toyId: number,
  params?: ToysDeleteToyParams,
  options?: RequestInit,
): Promise<null> => {
  const res = await fetch(getToysDeleteToyUrl(petId, toyId, params), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: null = body ? JSON.parse(body) : {};

  return data;
};

export const getToysDeleteToyMutationOptions = <
  TError = UnauthorizedError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toysDeleteToy>>,
    TError,
    { petId: number; toyId: number; params?: ToysDeleteToyParams },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof toysDeleteToy>>,
  TError,
  { petId: number; toyId: number; params?: ToysDeleteToyParams },
  TContext
> => {
  const mutationKey = ["toysDeleteToy"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof toysDeleteToy>>,
    { petId: number; toyId: number; params?: ToysDeleteToyParams }
  > = (props) => {
    const { petId, toyId, params } = props ?? {};

    return toysDeleteToy(petId, toyId, params, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ToysDeleteToyMutationResult = NonNullable<
  Awaited<ReturnType<typeof toysDeleteToy>>
>;

export type ToysDeleteToyMutationError = UnauthorizedError;

export const useToysDeleteToy = <
  TError = UnauthorizedError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toysDeleteToy>>,
    TError,
    { petId: number; toyId: number; params?: ToysDeleteToyParams },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationResult<
  Awaited<ReturnType<typeof toysDeleteToy>>,
  TError,
  { petId: number; toyId: number; params?: ToysDeleteToyParams },
  TContext
> => {
  const mutationOptions = getToysDeleteToyMutationOptions(options);

  return useMutation(mutationOptions);
};
