/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pet Store
 * OpenAPI spec version: 2.0
 */
import type { InternalServerError } from "./internalServerError";

export interface InternalServerErrorResponse {
  error: InternalServerError;
}
