/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pet Store
 * OpenAPI spec version: 2.0
 */
import type { NotFoundErrorCode } from "./notFoundErrorCode";

export interface NotFoundError {
  code: NotFoundErrorCode;
  message: string;
}
