/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pet Store
 * OpenAPI spec version: 2.0
 */
import type { PetType } from "./petType";

export interface Pet {
  id: number;
  /** @minLength 1 */
  name: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  age: number;
  kind: PetType;
}
