/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pet Store
 * OpenAPI spec version: 2.0
 */

export type PetType = (typeof PetType)[keyof typeof PetType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetType = {
  dog: "dog",
  cat: "cat",
  fish: "fish",
  bird: "bird",
  reptile: "reptile",
} as const;
