/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pet Store
 * OpenAPI spec version: 2.0
 */

export type UnauthorizedErrorCode =
  (typeof UnauthorizedErrorCode)[keyof typeof UnauthorizedErrorCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UnauthorizedErrorCode = {
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;
