/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pet Store
 * OpenAPI spec version: 2.0
 */

export type Versions = (typeof Versions)[keyof typeof Versions];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Versions = {
  "10": "1.0",
  "20": "2.0",
} as const;
