import * as mocks from "@/api/endpoints/index.msw";
import type { RequestHandler } from "msw";

// handlers that are automatically generated by Orval
const orvalHandlers: RequestHandler[] = Object.entries(mocks)
  .filter(([key, value]) => typeof value === "function" && key.endsWith("MockHandler"))
  .map(([, handler]) => handler() as RequestHandler);

// handlers that are manually created
const customHandlers: RequestHandler[] = [];

// This combines mock handlers (customHandlers first to override orvalHandlers if needed)
export const handlers: RequestHandler[] = [...customHandlers, ...orvalHandlers];
