import * as mocks from "@/api/endpoints/index.msw";
import type { RequestHandler } from "msw";

// handlers that are automatically generated by Orval
const orvalHandlers = Object.entries(mocks)
  .filter(([, value]) => typeof value === "function")
  .flatMap(([, getMock]) => (getMock as () => RequestHandler[])());

// handlers that are manually created
const customHandlers: RequestHandler[] = [];

// This combines mock handlers (customHandlers first to override orvalHandlers if needed)
export const handlers = [...customHandlers, ...orvalHandlers];
